config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :users
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :authors
  root 'books#index'

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
  <h1><%= link_to('Shaw Library', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Things to do...</h3>
    </div>
    <div class="panel-body">
      <p>
        <%= link_to 'All Books', books_path %>
      </p>
      <p>
        <%= link_to 'Authors', authors_path %>
      </p>
      <p>
        <%= link_to 'My Reservations', books_path %>
      </p>
      <% if session[:admin] %>
        <p>
          <%= link_to 'New Book', new_book_path %>
        </p>
        <p>
          <%= link_to 'Overdue Book', new_book_path %>
        </p>
      <% end %>
      <p>
        <%= button_to 'Logout', logout_path, method: :delete %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shaw Books <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <% if session[:user_id]  %>
      <div class="col-xs-3">
        <%= render '/layouts/sidebar' %>
      </div>
    <% end %>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>